import os

import tifffile  # type: ignore

from .hyperstack import Hyperstack

StrPath = os.PathLike | str


def read_ome(file_path: StrPath) -> Hyperstack:
    """Load an image hyperstack from an OME-TIFF file generated by micromanager 2.0.

    Parameters
    ----------
    file_path
        Path to image file to load.

    Returns
    -------
    images
        The image hyperstack.

    """
    # Load in the tiff file.
    with tifffile.TiffFile(file_path) as f:
        if len(f.series) > 1:
            raise tifffile.TiffFileError(
                f"Files with multiple series are not supported: {file_path}."
            )
        if f.micromanager_metadata is None or "Summary" not in f.micromanager_metadata:
            raise tifffile.TiffFileError(
                f"Different format from micromanager 2.0 OME-TIFF: {file_path}."
            )

        # We have a valid micromanager-generated file, read it into memory.
        channels = f.micromanager_metadata["Summary"].get("ChNames")
        return Hyperstack(f.series[0].asarray(), f.series[0].axes, channels)
